### ISSUE TITLE
cloud.gov and AWS support and transfer AWS accounts

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/fec-transition#137]
Research whether it is possible to transfer ownership of AWS accounts and adding support from cloud.gov to AWS. This is a research task that will allow us to make a plan.

**Comment by LindsayYoung** [comment]
Updating the ticket- this is possible, the next step is for FEC to procure an account

**Comment by LindsayYoung** [comment]
Sent billing data to FEC for their planning purposes

**Comment by PaulClark2** [comment]
RFQ is ready to send to procurement.

**Comment by PaulClark2** [comment]
Quotes are due May 4. We plan to award on 5/15.

**Comment by PaulClark2** [comment]
Contract for AWS services signed 6/21.
