### ISSUE TITLE
Purchase New Relic 

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/fec-transition#138]
Investigate cost

- [ ] Purchase New Relic
- [ ] licenses
- [ ] procurement process

**Comment by LindsayYoung** [comment]
OK, @PaulClark2 here is some relevant information that can help you choose what to buy:

We have 12 applications running.

Right now we are using APM and synthetics. APM is critical to fulfilling the monitoring part of the ATO. 

We need Synthetics but we could probably get by without synthetics pro for now, with regular synthetics we can have 50 pings, and we are using about 38 at the moment, in the future you might want more. We don't need any advanced checks.

We are enabled the browser features, but only in legal. We haven't been using them but they would be helpful if we had them enabled on fec-cms too.  

We have not been using mobile at all. 

If you buy the yearly plan it is cheaper.

**Comment by PaulClark2** [comment]
RFQ is ready to send to procurement.

**Comment by PaulClark2** [comment]
Draft RFP sent to contracting 3/14

**Comment by PaulClark2** [comment]
PR entered and awaiting approvals.

**Comment by JonellaCulmer** [comment]
@PaulClark2 Can we close this, or are we still waiting for approval? If still waiting, I can move this into 6.5.

**Comment by PaulClark2** [comment]
closed in favor of https://github.com/fecgov/openFEC/issues/3288
