### ISSUE TITLE
Create environment for classic.fec.gov

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/fec-transition#161]
So users can access classic.fec.gov after we shutdown our Waltham data center, we should host classic.fec.gov in an in alternative hosting center.

- [x] move equipment: one WEB, one APP, and one DB server from BO1 to DC3
    - [x] move scheduled during the week of 11/20
- [x ] install and configure equipment:  host equipment behind a firewall
- [ ] create and configure DB: similar to pubdb3z2 and push data to it from FECP
- [ ] create a read only standby database against the new database
- [ ] connect APP server to above standby database
- [ ] install and configure WAF

**Comment by rjayasekera** [comment]
Primary goal is to have two missing applications from the new fec.gov website
(fecviewer and data catalog pages) functionality available at the alternate site.
But most of the classic.gov functionality should be available at the new location. 

- [ ] Move one WEB, one APP, and one DB server from BO1 to DC3.
- [ ] Once the servers arrived at DC3 host them behind a firewall
- [ ] Create a small database similar to pubdb3z2 and push data to it from FECP
- [ ] Create a read only standby database against the new database.
- [ ] Connect APP server to above standby database.

**Comment by rjayasekera** [comment]
As of 11/28/17 WEB, APP, and Databases are mounted on a rack in DC3.  @gmengistu will power up assign new IP address and configure them on Monday 11/28/17

Next steps are:

- [ ] work out the network configuration, configure the switches and connect up all devices (Gashaw and Mark). 
- [ ] Assign IP addresses to the servers and boot them up  (Gashaw, Mark and Chris)  
- [ ] Rohan asked if we can configure db4 just like db3. We will look into cloning  the zones from db3 and put them on DB4. (Gashaw and Ron)

**Comment by gmengistu** [comment]
The web and app servers are up. The app server is connected to a read-only internal DB for testing while the new DB machines are being built. The network configuration is being worked on, but going a bit slow as Mark has been sick last week. We are not able to build the DBs before the network configuration is complete - but shouldn't be a show stopper as we have a connection to another database now - atleast for testing.

**Comment by PaulClark2** [comment]
@rjayasekera should this be closed?
