### ISSUE TITLE
GitHub transfer Part 1. "Lindsay Pushes the Button!" (thus transfering Non-code GitHUb repos to the FEC

### ISSUE THREAD

**Issue by jwchumley** [fecgov/fec-transition#168]
What we're after:
In order for FEC personnel to take ownership of the GitHub repository it needs to be transferred to the FEC.  Step one is to Transfer Non-code repos like FEC-epics,FEC-test etc. 

More details below.

- [x] Lindsay or Carlo pushes button
- [x] Confirm transfer

**Comment by LindsayYoung** [comment]
Here is the master ticket for all things that need to be transferred. https://github.com/18F/fec-transition/issues/155 (That is just for the overview to mark progress in a centralized place, not broken up for the task level like this ticket)

For purposes of this ticket the easy repos to transfer are:
- [ ]  fec-testing
- [ ]  fec-epics
- [ ]  fec-proxy
- [ ]  fec
   - [ ] Requires an env vars change for the feedback tool

**Comment by LindsayYoung** [comment]
Here is the documentation on how to transfer a repo https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/#transferring-to-an-organization

**Comment by LindsayYoung** [comment]
I think we will want a new key that should be generated by a FEC person for the fec repo

**Comment by LindsayYoung** [comment]
We can roll back permissions on fec-issues-bot (I can make a ticket) and this transfer should be pretty straight forward.

**Comment by LindsayYoung** [comment]
@patphongs just confirmed the transfer on the last repo in the list!
