### ISSUE TITLE
Wrap up open source policy

### ISSUE THREAD

**Issue by jwchumley** [fecgov/fec-transition#170]
Wrap up open source policy.

We have a draft reviewed by Jay. Paul needs to send it to OGC for their review.

Ideda: Promote open gov groups.

**Comment by PaulClark2** [comment]
OGC will have their review and comments back to me on 3/12.

**Comment by PaulClark2** [comment]
We have OGC's comments. I hope to review and integrate those comments into the policy sometime next week.

**Comment by PaulClark2** [comment]
I have some questions about OGC's comments related to accessibility .

**Comment by PaulClark2** [comment]
Yes

**Comment by PaulClark2** [comment]
PRs for this ticket:

https://github.com/fecgov/FEC/pull/7635
https://github.com/fecgov/FEC/pull/7634
https://github.com/fecgov/FEC/pull/7633

**Comment by PaulClark2** [comment]
published 7/31/18
