### ISSUE TITLE
Review and prioritize bugs (bug inventory)

### ISSUE THREAD

**Issue by jwchumley** [fecgov/fec-transition#175]
What we're after:
In order to ensure timely correction of bugs, we need to review the current set and categorize each one for priority and groom them so they will be ready when someone is available to work on them.  Partially in preparation for setting up a bug triage process.

Each existing bug issue is:
- [x] Prioritized
- [x] Groomed
- [x] Delete duplicates

**Comment by dorothyyeager** [comment]
Here's a bug from my issues: https://github.com/18F/fec-cms/issues/1694

**Comment by AmyKort** [comment]
We've groomed and prioritized the most pressing issues we need to address, and sent them to the top of the list. This is an open-ended task, since issues continue to come in. I suggest we close this ticket and adopt our bug review as a regular PM meeting task.
