### ISSUE TITLE
FEC documents fecgov GitHub organization

### ISSUE THREAD

**Issue by jwchumley** [fecgov/fec-transition#177]
What we're after:

In order to effectively administer GitHub, The FEC needs to know who will be admins for fecgov GitHub organization

PR is in: https://github.com/18F/fec-accounts/pull/106
- [X] make sure it is documented in FEC accounts
- [x] check w/Paul
 
Related: #178

**Comment by lbeaufort** [comment]
After our standup discussion 2/21, I'm going to try to help wrap this up this sprint.

**Comment by lbeaufort** [comment]
@PaulClark2  I think my PR is ready for your review: https://github.com/18F/fec-accounts/pull/106/files

**Comment by PaulClark2** [comment]
PR merged.
