### ISSUE TITLE
Review GitHub groups and permissions for FECGOV GitHub repo

### ISSUE THREAD

**Issue by jwchumley** [fecgov/fec-transition#178]
What we need:
In order to effectively administer GitHub we need to create GitHub groups for FEC.

- [ ] Read
- [ ] Write
- [ ] Admin

**Comment by patphongs** [comment]
We need to set read/write/admin permissions on a repository basis. This is so we can granularly limit access based on team's roles and responsibilities. 

- [ ] fec-testing
- [ ] fec-proxy
- [ ] fec-epics 
- [ ] fec-cms
- [ ] openFEC

**Comment by patphongs** [comment]
Permissions have been set on transferred repos. This ticket is completed for phase 1.
