### ISSUE TITLE
Create strategy for initiating Circle CI on FEC.GOV

### ISSUE THREAD

**Issue by jwchumley** [fecgov/fec-transition#186]
This relates to the master Github transfer checklist at 155. What we'll need to do is initiate the Circle work and transfer the variables. This is a master ticket to track work in these repos:

Completion criteria:
- [ ] OpenFEC
- [ ] FEC eRegs
- [ ] FEC CMS
- [ ] FEC Infrastructure
- [ ] FEC pattern library

Master list here: https://github.com/fecgov/fec-transition/issues/155https://github.com/fecgov/fec-transition/issues/155

**Comment by LindsayYoung** [comment]
@jwchumley want to break up these tickets by repo with each sub group of tasks for that repo. you can find the tasks grouped by repo in the master list. https://github.com/fecgov/fec-transition/issues/155

Also, here are the docs on adding circle badges https://circleci.com/docs/1.0/status-badges/
