### ISSUE TITLE
Define and communicate role of scrum master

### ISSUE THREAD

**Issue by jwchumley** [fecgov/fec-transition#202]
IN order to set up the first rotating scrum master for success we need to clearly design the roles and expectations.

- [x] define roles
- [x] communicate to the team
- [x] Have the first scrum master run two stand ups during sprint 6.3

**Comment by JonellaCulmer** [comment]
@PaulClark2 @jwchumley @AmyKort Below is a link to a few documents I compiled based on the discussion from yesterday's data issues meeting. This could be a good place to add further elaboration, if you decide it to be necessary, on the role of the scrum master. 

Please let me know which of the pending action items you'd like me to address. 
Scrum master folder:
https://drive.google.com/drive/folders/1fWFQH1wCPdXX7oGjHc_dcyjUrVOZd28A

Scrum master duties:
https://docs.google.com/document/d/16AnAhu1YcwuzG65abzfjqNCusnyrzexMccWwtxY-JZE/edit#

HIgh priority issue workflow: 
https://docs.google.com/document/d/11CRcubVqL9r6G2LlsEwEyK1Gh_qlXwxzLYrU-wbtR38/edit#heading=h.i4vv9croxub8

Scrum kick-off action items:
https://docs.google.com/document/d/1nIYD3pMcNtTUVgN4FVSpPEoV2D_e3YJk5iX3oxcLmXM/edit#

**Comment by AmyKort** [comment]
Thanks for the great information @JonellaCulmer . I'm going to close this ticket based on the discussion we had today.
